version: "3.6"

services:
  app:
    build: .
    env_file: .env
    ports:
      - "3000:3000"
    volumes:
      - app:/app
    depends_on:
      - db
    networks:
      - app_network
  
  db:
    image: postgres:9.6
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file: .env
    environment:
      POSTGRES_USER: computational_puzzles
      POSTGRES_PASSWORD: computational_puzzles # This is used to create development database, please change when migrate to production
    restart: always
    ports:
      - "35432:5432"
    networks:
      - app_network

volumes:
  app:
  db_data:

networks:
  app_network: