version: "3.6"

services:
  app:
    build: .
    env_file: .env
    ports:
      - "3000:3000"
    volumes:
      - app:/app
    networks:
      - app_network
  
  # db:
  #   image: postgres:9.6
  #   volumes:
  #     - db_data:/var/lib/postgresql/data
  #   env_file: .env
  #   ports:
  #     - "5432:5432"
  #   depends_on:
  #     - app
  #   networks:
  #     - app_network

volumes:
  app:
  # db_data:

networks:
  app_network: